name: Compile

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup SourcePawn Compiler
      id: setup
      uses: rumblefrog/setup-sp@v1.1.0
      with:
        version: "1.10.x"

    - name: Create plugins directory
      run: mkdir addons/sourcemod/plugins

    - name: Compile plugins
      run: |
        cd addons/sourcemod/scripting
        for file in *.sp; do spcomp $file -i "include" -o "../plugins/${file%.*}.smx"; done;

    - name: Upload GOKZ module
      uses: actions/upload-artifact@v3
      with:
        name: movementhud-module-gokz-git-${{ github.sha }}.smx
        path: addons/sourcemod/plugins/movementhud-module-gokz.smx

    - name: Upload KZTimer module
      uses: actions/upload-artifact@v3
      with:
        name: movementhud-module-kztimer-git-${{ github.sha }}.smx
        path: addons/sourcemod/plugins/movementhud-module-kztimer.smx
